apiVersion: v1
kind: Service
metadata:
  name: projeto
  labels:
    app: projeto
spec:
  type: NodePort
  selector:
    app: projeto
  ports:
  - port: 5001
    name: projeto-service
    targetPort: 8080
    nodePort: 31001