apiVersion: v1
kind: Service
metadata:
  name: projeto-svc
spec:
  selector:
    app: projeto
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto
spec:
  selector:
    matchLabels:
      app: projeto
  template:
    metadata:
      labels:
        app: projeto
    spec:
      containers:
      - name: projeto
        image: brianmorais/projetoexemploaspnet:latest
        resources:
          requests:
            memory: 100Mi
            cpu: 400m
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 8080

