apiVersion: v1
kind: Service
metadata:
  name: projet-svc
spec:
  selector:
    app: projeto
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto
spec:
  selector:
    matchLabels:
      app: projeto
  template:
    metadata:
      labels:
        app: projeto
    spec:
      containers:
      - name: projeto
        image: moraisbrian/projetoexemploaspnet:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

